sudo: required # necessary to add the sdl2-snapshots ppa
dist: trusty
language: rust

before_install:
  # sdl2 C libraries
  - sudo add-apt-repository ppa:zoogie/sdl2-snapshots -y
  - sudo apt-get update -q
  - hg clone https://hg.libsdl.org/SDL SDL
  - cd SDL && mkdir build && cd build
  - ../configure
  - make
  
install:
  # sdl2 C libraries, overwrite the default sdl2
  - sudo apt-get install libsdl2-ttf-dev libsdl2-image-dev
  - cd SDL/build
  - sudo make install

addons:
  apt:
    packages:
      # kcov compilation
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly
      env: FEATURES="--features clippy"
  allow_failures:
    - rust: nightly

# Better rust debugging info.
env:
  global:
    - RUST_BACKTRACE=1
    - RUSTFLAGS="-C link-dead-code"

branches:
  only:
    - master

# build, test and check benchmarks compile
script:
  # The first 2 steps is the same as the default build but with $FEATURES
  - cargo build --verbose $FEATURES
  - cargo test --verbose $FEATURES
  - 'if [ $TRAVIS_RUST_VERSION = nightly ]; then cargo bench --no-run; fi'

# After built rust and run the tests once, check the code coverage
after_success: |
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  cd kcov-master &&
  mkdir build &&
  cd build &&
  cmake .. &&
  make &&
  make install DESTDIR=../../kcov-build &&
  cd ../.. &&
  rm -rf kcov-master &&
  for file in target/debug/mazes-*[^\.d]; do mkdir -p "target/cov/$(basename $file)"; ./kcov-build/usr/local/bin/kcov --exclude-pattern=/.cargo,/usr/lib --verify "target/cov/$(basename $file)" "$file"; done &&
  bash <(curl -s https://codecov.io/bash) &&
  echo "Uploaded code coverage"
