language: rust
sudo: required
rust:
- beta
- nightly
- stable
install:
- sudo add-apt-repository ppa:debian-sid/ppa -y
- sudo apt-get update -q
- sudo apt-get install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
