sudo: false
addons:
 apt:
   sources:
   - ubuntu-toolchain-r-test
   packages:
   - libsdl2-dev
   - libsdl2-ttf-dev
   - libsdl2-image-dev
language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly

