sudo: required
language: rust
install:
- sudo add-apt-repository ppa:zoogie/sdl2-snapshots/ppa -y
- sudo apt-get update -q
- sudo apt-get install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev
- sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev
env:
  global:
    - LD_LIBRARY_PATH: /usr/local/lib
matrix:
    include:
        - rust: nightly
          env: FEATURES="--features clippy"
        - rust: beta
        - rust: stable
    allow_failures:
        - rust: nightly
script:
  - cargo build --verbose $FEATURES
  - cargo test --verbose $FEATURES
  - 'if [ $TRAVIS_RUST_VERSION = nightly ]; then cargo bench --no-run; fi'

after_success: |
    [ $TRAVIS_RUST_VERSION = stable ] &&
    wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
    tar xzf master.tar.gz && mkdir kcov-master/build && cd kcov-master/build && cmake .. && make && make install DESTDIR=../tmp && cd ../.. &&
    ls target/debug &&
    ./kcov-master/tmp/usr/local/bin/kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/hyper-* &&
    [ $TRAVIS_PULL_REQUEST = false ] &&
    [ $TRAVIS_RUST_VERSION = stable ]

