sudo: required # necessary to add the sdl2-snapshots ppa
language: rust

install:
# sdl2 C libraries
- sudo add-apt-repository ppa:zoogie/sdl2-snapshots/ppa -y
- sudo apt-get update -q
- sudo apt-get install libsdl2-dev libsdl2-ttf-dev libsdl2-image-dev
# For `travis-cargo coveralls` - coverage (kcov & coveralls.io) related packages
- sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev

matrix:
  include:
    - rust: nightly
      env: FEATURES="--features clippy"
    - rust: beta
    - rust: stable
  allow_failures:
    - rust: nightly

# load travis-cargo
before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

# Better rust debugging info.
env:
  global:
    - RUST_BACKTRACE=1

# build, test and check benchmarks compile
script:
  - cargo build --verbose $FEATURES
  - cargo test --verbose $FEATURES
  - 'if [ $TRAVIS_RUST_VERSION = nightly ]; then cargo bench --no-run; fi'

# Run tests again with kcov and upload coverage data to coveralls.io.
# A GH_TOKEN environment variable with a github personal access token (`public_repo` type) as the value (see github settings)
# is set in the Travis repository specific settings. Its value is set not to show up in the logs.
after_success:
  # upload the documentation from the build with stable (automatically only actually
  # runs on the master branch, not individual PRs)
  #- travis-cargo --only stable doc-upload
  # measure code coverage and upload to coveralls.io (the verify
  # argument mitigates kcov crashes due to malformed debuginfo, at the
  # cost of some speed <https://github.com/huonw/travis-cargo/issues/12>)
  - travis-cargo coveralls --no-sudo --verify
