cache:
    - c:\cargo\registry
    - c:\cargo\git

init:
    - mkdir c:\cargo
    - mkdir c:\rustup
    - SET PATH=c:\cargo\bin;%PATH%

environment:
    global:
        PROJECT_NAME: mazes
        RUST_BACKTRACE: full

    matrix:
        - TARGET: x86_64-pc-windows-msvc
          CHANNEL: stable
          BITS: 64
        - TARGET: i686-pc-windows-msvc
          CHANNEL: stable
          BITS: 32
        - TARGET:  x86_64-pc-windows-gnu
          CHANNEL: stable
          BITS: 64
          MSYS2: 1
        - TARGET: i686-pc-windows-gnu
          CHANNEL: stable
          BITS: 32
          MSYS2: 1

        - TARGET: x86_64-pc-windows-msvc
          CHANNEL: beta
          BITS: 64
        - TARGET: i686-pc-windows-msvc
          CHANNEL: beta
          BITS: 32
        - TARGET:  x86_64-pc-windows-gnu
          CHANNEL: beta
          BITS: 64
          MSYS2: 1
        - TARGET: i686-pc-windows-gnu
          CHANNEL: beta
          BITS: 32
          MSYS2: 1

        - TARGET: x86_64-pc-windows-msvc
          CHANNEL: nightly
          BITS: 64

matrix:
    fast_finish: true
    allow_failures:
        - channel: nightly

install:
    # Install rust for a given matrix combination of target + channel
    # Install clippy component
    - curl -sSf -o rustup-init.exe https://win.rustup.rs/
    - rustup-init.exe -y --default-host %TARGET% --default-toolchain %CHANNEL%
    - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
    - if defined MSYS2 set PATH=C:\msys64\mingw%BITS%\bin;%PATH%
    - rustup component add clippy
    - rustup component add rustfmt
    - rustc -vV
    - cargo -vV
    - rustup -vV

# Painfully long time required to find the setting for turning off msbuild and making it a script build is in the
# appveyor UI for the project. Build no. Test yes.
build_script:
    - cargo build --verbose

test_script:
    - cargo clippy -- -D warnings
    - cargo test --verbose
    - cargo bench --no-run

# Only build against the branches that will have pull requests built against them (master).
# Otherwise creating feature branches on this repository and a pull requests against them will
# cause each commit to be tested twice, once for the branch and once for the pull request.
branches:
  only:
    - master
