[package]
name = "mazes"
version = "0.1.0"
authors = ["enerqi <enerqi@enerqi>"]
repository = "https://github.com/enerqi/mazes.git"
homepage = "https://github.com/enerqi/mazes.git"
license = "MIT/Apache-2.0"

[dependencies]
bit-set = "^0.4.0"
docopt = "^0.8.0"
error-chain = "^0.10.0"
fnv = "^1.0.2"
image = "^0.13.0"
itertools = "^0.6.0"
lazy_static = "^0.2"
num = "^0.1.31"
petgraph = "^0.4.0"
rand = "^0.3.10"
serde = "^1.0"
serde_derive = "^1.0"
smallvec = "^0.4.0"

clippy = { version = "*", optional = true }

[dependencies.sdl2]
version = "^0.30.0"
default-features = false
features = ["image", "ttf"]

[dev-dependencies]
quickcheck = "^0.4.0"

[build-dependencies]
walkdir = "^1.0.3"

[features]
# Not using clippy by default: requires unstable compiler apis -> nightly rust build.
# Add `--features clippy` to the build or test command
default = []
test = []

[profile.release]
debug = true

[profile.bench]
debug = true

[[bin]]
name = "mazes_driver"
test = false
bench = false

[[bench]]
name = "generators"
path = "./benches/generators.rs"
test = false
bench = true
doc = false

[[bench]]
name = "grid"
path = "./benches/grid.rs"
test = false
bench = true
doc = false

[[bench]]
name = "masks"
path = "./benches/masks.rs"
test = false
bench = true
doc = false

[[bench]]
name = "pathing"
path = "./benches/pathing.rs"
test = false
bench = true
doc = false

[[bench]]
name = "renderers"
path = "./benches/renderers.rs"
test = false
bench = true
doc = false
