[package]
name = "mazes"
version = "0.1.0"
authors = ["enerqi <enerqi@enerqi>"]
build = "build.rs"
repository = "https://github.com/enerqi/mazes.git"
homepage = "https://github.com/enerqi/mazes.git"
license = "MIT/Apache-2.0"

[dependencies]
docopt = "0.6.78"
fnv = "1.0.2"
num = "0.1.31"
petgraph = "0.2.3"
rand = "0.3.10"
rustc-serialize = "0.3.18"
sdl2 = "0.16.0"
sdl2_image = "1.1.0"
sdl2_ttf = "0.15.0"
smallvec = "0.1.6"

clippy = { version = "*", optional = true }
quickcheck = { version = "*", optional = true }

[dev-dependencies]
itertools = "0.4.6"

[features]
# Not using clippy by default: requires unstable compiler apis -> nightly rust build.
# Add `--features clippy` to the build or test command
default = []
test = []

[[bin]]
name = "mazes_driver"
