# http://doc.crates.io/manifest.html#the-project-layout
# - Cargo.toml contains the broad dependencies description
# - We source control Cargo.lock only for executables
# which this project uses, so don't put in .gitignore
[package]
name = "mazes"
version = "0.1.0"
authors = ["enerqi <enerqi@enerqi>"]
build = "build.rs"

[dependencies]
docopt = "0.6.78"
fnv = "1.0.2"
num = "0.1.31"
petgraph = "0.2.2"
rand = "0.3.10"
rustc-serialize = "0.3.18" # "0.3" `derive(RustcEncodable, RustcDecodable)` and hex, base64, and json encoding and decoding.
sdl2 = "0.16.0"
sdl2_image = "1.1.0"
sdl2_ttf = "0.15.0"
smallvec = "0.1.6"

clippy = { version = "*", optional = true }

[features]
# Not using clippy by default: requires unstable compiler apis -> nightly rust build.
# Add `--features clippy` to the build or test command
default = []

[dev-dependencies]
itertools = "0.4.6"
