# http://doc.crates.io/manifest.html#the-project-layout
# - Cargo.toml contains the broad dependencies description
# - We source control Cargo.lock only for executables
# which this project uses, so don't put in .gitignore
[package]
name = "mazes"
version = "0.1.0"
authors = ["enerqi <enerqi@enerqi>"]
build = "build.rs"

[dependencies]
petgraph = "0.2.2"
rand = "0.3.10"
sdl2 = "0.13.0"
sdl2_image = "1.0.0"
sdl2_ttf = "0.14.0"

clippy = { version = "*", optional = true }

[features]
# Not using clippy by default: requires unstable compiler apis -> nightly rust build.
# Add `--features clippy` to the build or test command
default = []

[dev-dependencies]
itertools = "0.4.6"
